// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfzIpk1ngCUpv-lFlPg52aQYLSuVl8aAc',
    appId: '1:722386718485:web:fc27f48b02de499553231c',
    messagingSenderId: '722386718485',
    projectId: 'postercreate-469fc',
    authDomain: 'postercreate-469fc.firebaseapp.com',
    storageBucket: 'postercreate-469fc.firebasestorage.app',
    measurementId: 'G-VME38YT3GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHb7dPHdVLTBYepivxgQUr8hNp2gDRQD8',
    appId: '1:722386718485:android:2ef26a0e2bbfcf1053231c',
    messagingSenderId: '722386718485',
    projectId: 'postercreate-469fc',
    storageBucket: 'postercreate-469fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClE7jpFRLSVh39zlJm7dijzAKPGFzFZRw',
    appId: '1:722386718485:ios:122bb374d72ec7bc53231c',
    messagingSenderId: '722386718485',
    projectId: 'postercreate-469fc',
    storageBucket: 'postercreate-469fc.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClE7jpFRLSVh39zlJm7dijzAKPGFzFZRw',
    appId: '1:722386718485:ios:122bb374d72ec7bc53231c',
    messagingSenderId: '722386718485',
    projectId: 'postercreate-469fc',
    storageBucket: 'postercreate-469fc.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfzIpk1ngCUpv-lFlPg52aQYLSuVl8aAc',
    appId: '1:722386718485:web:43af548206e4c06953231c',
    messagingSenderId: '722386718485',
    projectId: 'postercreate-469fc',
    authDomain: 'postercreate-469fc.firebaseapp.com',
    storageBucket: 'postercreate-469fc.firebasestorage.app',
    measurementId: 'G-22QC9G67FP',
  );
}
